language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sriniv23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sriniv23/react-test npm test

after_success:
  - docker build -t sriniv23/multi-client ./client
  - docker build  -t sriniv23/multi-nginx ./nginx
  - docker build -t sriniv23/multi-server ./server
  - docker build -t sriniv23/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sriniv23/multi-client
  - docker push sriniv23/multi-nginx
  - docker push sriniv23/multi-server
  - docker push sriniv23/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env-1
  bucket_name: elasticbeanstalk-us-west-2-139793558214
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY